/**
 * This is a manually typed mapping of Flatpickr to MomentJS locale.
 * Once MomentJS or Flatpickr get a new language add it here.
 */

export const flatpickrLocaleMapping = {
    default:  {translation: "en-gb", name: "english"},
    ar:       {translation: "ar", name: "Arabic"},
    at:       {translation: "de-at", name: "Austria"},
    az:       {translation: "az", name: "Azerbaijan"},
    be:       {translation: "be", name: "Belarusian"},
    bg:       {translation: "bg", name: "Bulgarian"},
    bn:       {translation: "bn", name: "Bangla"},
    bs:       {translation: "bs", name: "Bosnian"},
    cat:      {translation: "ca", name: "Catalan"},
    cs:       {translation: "cs", name: "Czech"},
    cy:       {translation: "cy", name: "Welsh"},
    da:       {translation: "da", name: "Danish"},
    de:       {translation: "de", name: "German"},
    eo:       {translation: "eo", name: "Esperanto"},
    es:       {translation: "es", name: "Spanish"},
    et:       {translation: "et", name: "Estonian"},
    fa:       {translation: "fa", name: "Persian"},
    fi:       {translation: "fi", name: "Finnish"},
    fo:       {translation: "fo", name: "Faroese"},
    fr:       {translation: "fr", name: "French"},
    ga:       {translation: "ga", name: "Irish"},
    gr:       {translation: "el", name: "Greek"},
    he:       {translation: "he", name: "Hebrew"},
    hi:       {translation: "hi", name: "Hindi"},
    hr:       {translation: "hr", name: "Croatian"},
    hu:       {translation: "hu", name: "Hungarian"},
    id:       {translation: "id", name: "Indonesian"},
    is:       {translation: "is", name: "Icelandic"},
    it:       {translation: "it", name: "Italian"},
    ja:       {translation: "ja", name: "Japanese"},
    ka:       {translation: "ka", name: "Georgian"},
    km:       {translation: "km", name: "Khmer"},
    ko:       {translation: "ko", name: "Korean"},
    kz:       {translation: "kk", name: "Kazakh"},
    lt:       {translation: "lt", name: "Lithuanian"},
    lv:       {translation: "lv", name: "Latvian"},
    mk:       {translation: "mk", name: "Macedonian"},
    mn:       {translation: "mn", name: "Mongolian"},
    ms:       {translation: "ms", name: "Malaysian"},
    my:       {translation: "my", name: "Burmese"},
    nl:       {translation: "nl", name: "Dutch"},
    no:       {translation: "nb", name: "Norwegian"},
    pa:       {translation: "pa-in", name: "Punjabi"},
    pl:       {translation: "pl", name: "Polish"},
    pt:       {translation: "pt", name: "Portuguese"},
    ro:       {translation: "ro", name: "Romanian"},
    ru:       {translation: "ru", name: "Russian"},
    si:       {translation: "si", name: "Sinhala"},
    sk:       {translation: "sk", name: "Slovak"},
    sl:       {translation: "sl", name: "Slovenian"},
    sq:       {translation: "sq", name: "Albanian"},
    sr:       {translation: "sr", name: "Serbian"},
    "sr-cyr": {translation: "sr-cyrl", name: "SerbianCyrillic"},
    sv:       {translation: "sv", name: "Swedish"},
    th:       {translation: "th", name: "Thai"},
    tr:       {translation: "tr", name: "Turkish"},
    uk:       {translation: "uk", name: "Ukrainian"},
    vn:       {translation: "vi", name: "Vietnamese"},
    zh:       {translation: "zh-cn", name: "Mandarin"},
    "zh-tw":  {translation: "zh-tw", name: "MandarinTraditional"},
}

export const momentjsLocaleMapping = {
    ar:        {translation: "ar"},
    az:        {translation: "az"},
    be:        {translation: "be"},
    bg:        {translation: "bg"},
    bn:        {translation: "bn"},
    bs:        {translation: "bs"},
    ca:        {translation: "cat"},
    cs:        {translation: "cs"},
    cy:        {translation: "cy"},
    da:        {translation: "da"},
    de:        {translation: "de"},
    "de-at":   {translation: "at"},
    "de-ch":   {translation: "de"},
    el:        {translation: "gr"},
    en:        {translation: "default"},
    "en-au":   {translation: "default"},
    "en-ca":   {translation: "default"},
    "en-gb":   {translation: "default"},
    "en-ie":   {translation: "default"},
    "en-nz":   {translation: "default"},
    eo:        {translation: "eo"},
    es:        {translation: "es"},
    "es-do":   {translation: "es"},
    "es-us":   {translation: "es"},
    et:        {translation: "et"},
    fa:        {translation: "fa"},
    fi:        {translation: "fi"},
    fo:        {translation: "fo"},
    fr:        {translation: "fr"},
    "fr-ca":   {translation: "fr"},
    "fr-ch":   {translation: "fr"},
    ga:        {translation: "ga"},
    he:        {translation: "he"},
    hi:        {translation: "hi"},
    hr:        {translation: "hr"},
    hu:        {translation: "hu"},
    id:        {translation: "id"},
    is:        {translation: "is"},
    it:        {translation: "it"},
    ja:        {translation: "ja"},
    ka:        {translation: "ka"},
    kk:        {translation: "kz"},
    km:        {translation: "km"},
    ko:        {translation: "ko"},
    lt:        {translation: "lt"},
    lv:        {translation: "lv"},
    mk:        {translation: "mk"},
    mn:        {translation: "mn"},
    ms:        {translation: "ms"},
    my:        {translation: "my"},
    nb:        {translation: "no"},
    nl:        {translation: "nl"},
    "pa-in":   {translation: "pa"},
    pl:        {translation: "pl"},
    pt:        {translation: "pt"},
    "pt-br":   {translation: "pt"},
    ro:        {translation: "ro"},
    ru:        {translation: "ru"},
    si:        {translation: "si"},
    sk:        {translation: "sk"},
    sl:        {translation: "sl"},
    sq:        {translation: "sq"},
    sr:        {translation: "sr"},
    "sr-cyrl": {translation: "sr-cyr"},
    sv:        {translation: "sv"},
    th:        {translation: "th"},
    tr:        {translation: "tr"},
    uk:        {translation: "uk"},
    vi:        {translation: "vn"},
    "zh-cn":   {translation: "zh"},
    "zh-hk":   {translation: "zh"},
    "zh-tw":   {translation: "zh-tw"},
}
