/**
 * This is a manually typed mapping of Flatpickr to MomentJS locale.
 * Once MomentJS or Flatpickr get a new language add it here.
 */

export const flatpickrLocaleMapping = {
    default: {translation: 'en-gb', name: 'english'},
    hr:      {translation: 'hr', name: 'Croatian'},
    th:      {translation: 'th', name: 'Thai'},
    tr:      {translation: 'tr', name: 'Turkish'},
    ar:      {translation: 'ar', name: 'Arabic'},
    at:      {translation: 'de-at', name: 'Austria'},
    be:      {translation: 'be', name: 'Belarusian'},
    bg:      {translation: 'bg', name: 'Bulgarian'},
    bn:      {translation: 'bn', name: 'Bangla'},
    cat:     {translation: 'ca', name: 'Catalan'},
    cs:      {translation: 'cs', name: 'Czech'},
    cy:      {translation: 'cy', name: 'Welsh'},
    da:      {translation: 'da', name: 'Danish'},
    de:      {translation: 'de', name: 'German'},
    eo:      {translation: 'eo', name: 'Esperanto'},
    es:      {translation: 'es', name: 'Spanish'},
    et:      {translation: 'et', name: 'Estonian'},
    fa:      {translation: 'fa', name: 'Persian'},
    fi:      {translation: 'fi', name: 'Finnish'},
    fr:      {translation: 'fr', name: 'French'},
    gr:      {translation: 'el', name: 'Greek'},
    he:      {translation: 'he', name: 'Hebrew'},
    hi:      {translation: 'hi', name: 'Hindi'},
    hu:      {translation: 'hu', name: 'Hungarian'},
    id:      {translation: 'id', name: 'Indonesian'},
    it:      {translation: 'it', name: 'Italian'},
    ja:      {translation: 'ja', name: 'Japanese'},
    ko:      {translation: 'ko', name: 'Korean'},
    km:      {translation: 'km', name: 'Khmer'},
    kz:      {translation: 'kk', name: 'Kazakh'},
    lt:      {translation: 'lt', name: 'Lithuanian'},
    lv:      {translation: 'lv', name: 'Latvian'},
    mk:      {translation: 'mk', name: 'Macedonian'},
    ms:      {translation: 'ms', name: 'Malaysian'},
    my:      {translation: 'my', name: 'Burmese'},
    nl:      {translation: 'nl', name: 'Dutch'},
    no:      {translation: 'nb', name: 'Norwegian'},
    pa:      {translation: 'pa-in', name: 'Punjabi'},
    pl:      {translation: 'pl', name: 'Polish'},
    pt:      {translation: 'pt', name: 'Portuguese'},
    ro:      {translation: 'ro', name: 'Romanian'},
    ru:      {translation: 'ru', name: 'Russian'},
    si:      {translation: 'si', name: 'Sinhala'},
    sk:      {translation: 'sk', name: 'Slovak'},
    sl:      {translation: 'sl', name: 'Slovenian'},
    sq:      {translation: 'sq', name: 'Albanian'},
    sr:      {translation: 'sr', name: 'Serbian'},
    sv:      {translation: 'sv', name: 'Swedish'},
    uk:      {translation: 'uk', name: 'Ukrainian'},
    vn:      {translation: 'vi', name: 'Vietnamese'},
    zh:      {translation: 'zh-cn', name: 'Mandarin'},
}

export const momentjsLocaleMapping = {
    hr:      {translation: 'hr'},
    th:      {translation: 'th'},
    tr:      {translation: 'tr'},
    ar:      {translation: 'ar'},
    be:      {translation: 'be'},
    bg:      {translation: 'bg'},
    bn:      {translation: 'bn'},
    ca:      {translation: 'cat'},
    cs:      {translation: 'cs'},
    cy:      {translation: 'cy'},
    da:      {translation: 'da'},
    de:      {translation: 'de'},
    'de-at': {translation: 'at'},
    'de-ch': {translation: 'de'},
    'en-ca': {translation: 'default'},
    'en-au': {translation: 'default'},
    'en-gb': {translation: 'default'},
    'en-ie': {translation: 'default'},
    'en-nz': {translation: 'default'},
    eo:      {translation: 'eo'},
    es:      {translation: 'es'},
    'es-do': {translation: 'es'},
    'es-us': {translation: 'es'},
    et:      {translation: 'et'},
    fa:      {translation: 'fa'},
    fi:      {translation: 'fi'},
    fr:      {translation: 'fr'},
    'fr-ca': {translation: 'fr'},
    'fr-ch': {translation: 'fr'},
    el:      {translation: 'gr'},
    he:      {translation: 'he'},
    hi:      {translation: 'hi'},
    hu:      {translation: 'hu'},
    id:      {translation: 'id'},
    it:      {translation: 'it'},
    ja:      {translation: 'ja'},
    ko:      {translation: 'ko'},
    km:      {translation: 'km'},
    kk:      {translation: 'kz'},
    lt:      {translation: 'lt'},
    lv:      {translation: 'lv'},
    mk:      {translation: 'mk'},
    ms:      {translation: 'ms'},
    my:      {translation: 'my'},
    nl:      {translation: 'nl'},
    nb:      {translation: 'no'},
    'pa-in': {translation: 'pa'},
    pl:      {translation: 'pl'},
    pt:      {translation: 'pt'},
    ro:      {translation: 'ro'},
    ru:      {translation: 'ru'},
    si:      {translation: 'si'},
    sk:      {translation: 'sk'},
    sl:      {translation: 'sl'},
    sq:      {translation: 'sq'},
    sr:      {translation: 'sr'},
    sv:      {translation: 'sv'},
    uk:      {translation: 'uk'},
    vi:      {translation: 'vn'},
    'zh-cn': {translation: 'zh'},
    'zh-hk': {translation: 'zh'},
    'zh-tw': {translation: 'zh'},
}
